proxy:
  secretToken: "a9d95455a8e49391ac7f5384803fe2d415ec50c835bb47398ec99d8baf7f966f"
  https:
    hosts:
      - instructor.humbio51.net
    letsencrypt:
      contactEmail: 'annashcherbina@gmail.com'
  service:
    loadBalancerIP: 34.70.187.230


singleuser:
  defaultUrl: "/lab"
  storage:
    extraVolumes:
      - name: pv-claim-demo-2
        persistentVolumeClaim:
          claimName: pv-claim-demo-2
          readOnly: true
    extraVolumeMounts:
      - name: pv-claim-demo-2
        mountPath: /data
        readOnly: true  
  image:
    name: kundajelab/humbio51
    tag: 7dbd3127232c
  lifecycle:
    postStart:
      exec:
        command:
          - "sh"
          - "-c"
          - >
            gitpuller https://github.com/kundajelab/humbio51 master humbio51_instructor;
            gitpuller https://github.com/kundajelab/humbio51 student humbio51_student            
hub:
  extraConfig:
    jupyterlab: |
      c.Spawner.cmd = ['jupyter-labhub']

ingress:
  annotations:
    kubernetes.io/tls-acme: "true"
  tls:
   - hosts:
      - instructor.humbio51.net
     secretName: kubelego-tls-jupyterhub
auth:
  type: github
  github:
    clientId: eaa6c2a265ba334781aa
    clientSecret: d1bd12a065ed46b916e7a5540b298775df533eab
    callbackUrl: https://instructor.humbio51.net/hub/oauth_callback
  admin:
    access: true
    users:
      - annashcherbina
      - asalmeen
      - akundaje
      - soumyakundu
  whitelist:
    users:
      - annashcherbina
      - asalmeen
      - akundaje
      - soumyakundu

scheduling:
  userScheduler:
    enabled: true
  podPriority:
    enabled: true
  userPlaceholder:
    enabled: true
    replicas: 2
  userPods:
    nodeAffinity:
      matchNodePurpose: require
      
cull:
  enabled: true
  timeout: 1800
  every: 180

