proxy:
  secretToken: "4c06e39d620c54ee78319a6ac36a4d168bd7b829b79d76aeb414de4877ba9bea"
singleuser:
  defaultUrl: "/lab"
  image:
    name: kundajelab/humbio51
    tag: latest

hub:
  extraConfig:
    jupyterlab: |
      c.Spawner.cmd = ['jupyter-labhub']
cull:
  enabled: false

auth:
  type: lti
  lti:
    consumers:
      c5a9d574fba4b6aa7088df10e48e806d076a2cab57e17f0b93fedd2c3f18b6b8: 447c43cc59e3e465e43a00ba6f1ee4f5445c2aee5cd56ae622e0bd1039d60bd5
  admin:
    users:
      ["30481"]
