proxy:
  secretToken: "4c06e39d620c54ee78319a6ac36a4d168bd7b829b79d76aeb414de4877ba9bea"
  https:
    hosts:
      - humbio51.net
    letsencrypt:
      contactEmail: 'annashcherbina@gmail.com'
  service:
    loadBalancerIP: 35.239.194.45
    
singleuser:
  cpu:
    limit: 4
    guarantee: 1
  memory:
    limit: 4G
    guarantee: 512M
  image:
    name: kundajelab/humbio51
    tag: eb5c0a2e27fb
  storage:
    extraVolumes:
      - name: humbio51-data-disk
        persistentVolumeClaim:
          claimName: humbio51-data-disk
          readOnly: true
    extraVolumeMounts:
      - name: humbio51-data-disk
        mountPath: /data
               
hub:
  extraConfig:
    jupyterlab: |
      c.Spawner.cmd = ['jupyter-labhub']

ingress:
  annotations:
    kubernetes.io/tls-acme: "true"
  tls:
   - hosts:
      - humbio51.net
     secretName: kubelego-tls-jupyterhub
 
auth:
  type: lti
  lti:
    consumers:
      c5a9d574fba4b6aa7088df10e48e806d076a2cab57e17f0b93fedd2c3f18b6b8: 447c43cc59e3e465e43a00ba6f1ee4f5445c2aee5cd56ae622e0bd1039d60bd5
  admin:
    users:
      ["30481","14552"]
    access: true

cull:
  enabled: true
  timeout: 3600
  every: 300

