proxy:
  secretToken: "4c06e39d620c54ee78319a6ac36a4d168bd7b829b79d76aeb414de4877ba9bea"
singleuser:
  defaultUrl: "/lab"

hub:
  extraConfig:
    jupyterlab: |
      c.Spawner.cmd = ['jupyter-labhub']
cull:
  enabled: false

auth:
  admin:
    users:
      - annashch
      - akundaje
      - asalmeen
      - soumyak
      