proxy:
  secretToken: "a9d95455a8e49391ac7f5384803fe2d415ec50c835bb47398ec99d8baf7f966f"
  https:
    hosts:
      - instructor.humbio51.net
    letsencrypt:
      contactEmail: 'annashcherbina@gmail.com'
  service:
    loadBalancerIP: 34.70.187.230


singleuser:
  defaultUrl: "/lab"
  image:
    name: kundajelab/humbio51
    tag: d0049b9d1de1
  lifecycleHooks:
    postStart:
      exec:
        command: ["gitpuller", "https://github.com/kundajelab/humbio51", "master", "humbio51"]
  storage:
    extraVolumes:
      - name: humbio51-data-disk
        persistentVolumeClaim:
          claimName: humbio51-data-disk
          #readOnly: true
    extraVolumeMounts:
      - name: humbio51-data-disk
        mountPath: /data        
hub:
  extraConfig:
    jupyterlab: |
      c.Spawner.cmd = ['jupyter-labhub']

ingress:
  annotations:
    kubernetes.io/tls-acme: "true"
  tls:
   - hosts:
      - instructor.humbio51.net
     secretName: kubelego-tls-jupyterhub
auth:
  type: github
  github:
    clientId: eaa6c2a265ba334781aa
    clientSecret: d1bd12a065ed46b916e7a5540b298775df533eab
    callbackUrl: https://instructor.humbio51.net/hub/oauth_callback
  admin:
    access: true
    users:
      - annashcherbina
      - asalmeen
      - akundaje
      - soumyak
cull:
  enabled: true
  timeout: 3600
  every: 300

