apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-demo-2
spec:
  # It's necessary to specify "" as the storageClassName
  # so that the default storage class won't be used, see
  # https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class-1
  storageClassName: ""
  volumeName: pv-demo-2
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 40G
