proxy:
  secretToken: "cdc823015efcd715b435a79f467aba5ffbd56fa6caa53f0a9abee0fe361eacc9"
  https:
    enabled: false
    hosts:
      - humbio51.net
    letsencrypt:
      contactEmail: 'annashcherbina@gmail.com'
  service:
    loadBalancerIP: 35.222.2.245

scheduling:
  userScheduler:
    enabled: false
  podPriority:
    enabled: true
  userPlaceholder:
    enabled: true
    replicas: 2
  userPods:
    nodeAffinity:
      matchNodePurpose: require
        
singleuser:
  image:
    name: kundajelab/humbio51
    tag: latest
  storage:
    capacity: 5Gi
    extraVolumes:
      - name: humbio51-data-pvc
        persistentVolumeClaim:
          claimName: humbio51-data-pvc
          readOnly: true
    extraVolumeMounts:
      - name: humbio51-data-pvc
        mountPath: /data
        readOnly: true


hub:
  extraConfig:
    jupyterlab: |
      c.Spawner.cmd = ['jupyter-labhub']

auth:
  type: lti
  lti:
    consumers:
      c5a9d574fba4b6aa7088df10e48e806d076a2cab57e17f0b93fedd2c3f18b6b8: 447c43cc59e3e465e43a00ba6f1ee4f5445c2aee5cd56ae622e0bd1039d60bd5
  admin:
    users:
      ["30481","14552", "183448"]
    access: true
      
cull:
  enabled: true
  timeout: 1800
  every: 180

