apiVersion: v1
kind: PersistentVolume
metadata:
  name: humbio51-data-instructor-pv
spec:
  storageClassName: ""
  claimRef:
    name: humbio51-data-instructor-pvc
    namespace: jhub-instructor 
  capacity:
    storage: 40G
  accessModes:
    - ReadOnlyMany
  gcePersistentDisk:
    pdName: humbio51-data-instructor-pv-persistentdisk
    fsType: ext4

